---
driver:
  name: vagrant
driver_config:
  customize:
    # Configure network interface to use hosts DNS resolver.  Doing this makes installing Gems and other network tasks significantly faster.
    natdnsproxy1: 'off'
    natdnshostresolver1: 'off'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      # We only include apt because of an issue installing java where ubuntu
      # requires an apt-get update in order to successfully run
      - recipe[apt]
      - recipe[apache_zookeeper::install]
      - recipe[apache_zookeeper::configure]
      - recipe[apache_zookeeper::service]
    attributes:
      java:
        jdk_version: "7"
      apache_zookeeper:
        install_java: true
        zoo.cfg:
          bogus.for.cfg: value1
        log4j.properties:
          bogus.for.log4j: value2
